{{- range .Values.vpManageProxyClusterCa.pushAdditionalCMCAs }}
---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: {{ .name }}-ps
  namespace: {{ .namespace }}
spec:
  updatePolicy: Replace
  deletionPolicy: Delete
  refreshInterval: {{ $.Values.vpManageProxyClusterCa.pushSecretRefreshInterval }}
  secretStoreRefs:
    - kind: ClusterSecretStore
      name: vault-backend
  selector:
    secret:
      name: {{ .name }}-intermediary
  data:
    - conversionStrategy: None
      match:
        secretKey: {{ .key }}
        remoteRef:
          remoteKey: pushsecrets/{{ $.Values.global.clusterDomain }}-{{ .name }}-{{ $.Values.vpManageProxyClusterCa.pushSecretPostfix }}
          property: cert
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .name }}-intermediary
  namespace: {{ .namespace }}
spec:
  refreshInterval: {{ $.Values.vpManageProxyClusterCa.pushSecretRefreshInterval }}
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: {{ .name }}-intermediary
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      mergePolicy: Merge
      engineVersion: v2
      templateFrom:
      - target: Data
        configMap:
          # name of the configmap to pull in
          name: {{ .name }}
          # here you define the keys that should be used as template
          items:
          - key: {{ .key }}
            templateAs: Values
  data:
  # TODO FIX this needs to point to secret in vault
  - secretKey: asd
    remoteRef:
      key: "global/config-demo"
      property: secret
{{- end }}
