{{- range .Values.vpManageProxyClusterCa.pushAdditionalSecretCAs }}
---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: {{ .name }}-ps
  namespace: {{ .namespace }}
spec:
  updatePolicy: Replace
  deletionPolicy: Delete
  refreshInterval: {{ $.Values.vpManageProxyClusterCa.pushSecretRefreshInterval }}
  secretStoreRefs:
    - kind: ClusterSecretStore
      name: vault-backend
  selector:
    secret:
      name: {{ .name }}
  data:
    - conversionStrategy: None
      match:
        secretKey: {{ .key }}
        remoteRef:
          remoteKey: pushsecrets/{{ $.Values.global.clusterDomain }}-{{ .name }}-{{ $.Values.vpManageProxyClusterCa.pushSecretPostfix }}
          property: cert
{{- end }}




