---
global:
  pattern: multicloud-gitops
  options:
    useCSV: false
    syncPolicy: Automatic
    installPlanApproval: Automatic

main:
  clusterGroupName: hub
  multiSourceConfig:
    enabled: true
    clusterGroupGitRepoUrl: https://github.com/darkdoc/clustergroup-chart
    clusterGroupChartGitRevision: k8s_kind
  gitops:
    channel: alpha
    sourceNamespace: olm
    operatorSource: operatorhubio-catalog
    name: argocd-operator
  patternsOperator:
    source: operatorhubio-catalog
    sourceNamespace: olm

