---
global:
  pattern: multicloud-gitops
  options:
    useCSV: false
    syncPolicy: Automatic
    installPlanApproval: Automatic

main:
  clusterGroupName: hub
  # This way we can install the customer operator via ./hack/operator-build-script.sh
  # and then install this pattern via ./pattern.sh make install
  patternsOperator:
    enableSubscription: false
    subscriptionNamespace: patterns-operator
  multiSourceConfig:
    enabled: true
    clusterGroupGitRepoUrl: https://github.com/darkdoc/clustergroup-chart
    clusterGroupChartGitRevision: k8s_kind
  gitops:
    channel: alpha
    sourceNamespace: olm
    operatorSource: operatorhubio-catalog
    packageName: argocd-operator
  # patternsOperator:
  #   source: operatorhubio-catalog
  #   sourceNamespace: olm

