---
global:
  pattern: multicloud-gitops
  options:
    useCSV: false
    syncPolicy: Automatic
    installPlanApproval: Automatic

main:
  clusterGroupName: hub
  multiSourceConfig:
    enabled: true
    clusterGroupChartVersion: "0.9.*"
  gitops:
    channel: alpha
    sourceNamespace: olm
    operatorSource: operatorhubio-catalog
    name: argocd-operator
  patternsOperator:
    source: operatorhubio-catalog
    sourceNamespace: olm
